library(tidyverse)

## ---- simulation_recovery_result_matrix ----

study_1_results <- tribble(
  ~Algoritmo,      ~Parametro,   ~Variable,      ~Nivel,  ~Estadistico, ~Valor,
      "MCMC", "Correlaciones",      "OPBP",       "2/3",        "RMSE",   .040,
      "MCMC", "Correlaciones",      "OPBP",       "1/3",        "RMSE",   .040,
      "MCMC", "Correlaciones",      "OPBP",         "0",        "RMSE",   .055,
      "MCMC", "Rasgo latente",      "OPBP",       "2/3",        "RMSE",   .433,
      "MCMC", "Rasgo latente",      "OPBP",       "1/3",        "RMSE",   .438,
      "MCMC", "Rasgo latente",      "OPBP",         "0",        "RMSE",   .544,
      "MCMC", "Rasgo latente",      "OPBP",       "2/3",  "Fiabilidad",   .810,
      "MCMC", "Rasgo latente",      "OPBP",       "1/3",  "Fiabilidad",   .806,
      "MCMC", "Rasgo latente",      "OPBP",         "0",  "Fiabilidad",   .700,
      "MCMC", "Rasgo latente", "OPBP x QL",  "2/3 x 18",  "Fiabilidad",   .762,
      "MCMC", "Rasgo latente", "OPBP x QL",  "1/3 x 18",  "Fiabilidad",   .756,
      "MCMC", "Rasgo latente", "OPBP x QL",    "0 x 18",  "Fiabilidad",   .633,
      "MCMC", "Rasgo latente", "OPBP x QL",  "2/3 x 36",  "Fiabilidad",   .858,
      "MCMC", "Rasgo latente", "OPBP x QL",  "1/3 x 36",  "Fiabilidad",   .856,
      "MCMC", "Rasgo latente", "OPBP x QL",    "0 x 36",  "Fiabilidad",   .768,
      "MCMC",       "Escalas",      "OPBP",       "2/3", "Correlación",   .994,
      "MCMC",       "Escalas",      "OPBP",       "1/3", "Correlación",   .992,
      "MCMC",       "Escalas",      "OPBP",         "0", "Correlación",   .972,
       "CFA", "Correlaciones",      "OPBP",       "2/3",        "RMSE",   .043,
       "CFA", "Correlaciones",      "OPBP",       "1/3",        "RMSE",   .042,
       "CFA", "Correlaciones",      "OPBP",         "0",        "RMSE",   .081,
       "CFA", "Rasgo latente",      "OPBP",       "2/3",        "RMSE",   .434,
       "CFA", "Rasgo latente",      "OPBP",       "1/3",        "RMSE",   .439,
       "CFA", "Rasgo latente",      "OPBP",         "0",        "RMSE",   .548,
       "CFA", "Rasgo latente",      "OPBP",       "2/3",  "Fiabilidad",   .809,
       "CFA", "Rasgo latente",      "OPBP",       "1/3",  "Fiabilidad",   .805,
       "CFA", "Rasgo latente",      "OPBP",         "0",  "Fiabilidad",   .695,
       "CFA", "Rasgo latente", "OPBP x QL",  "2/3 x 18",  "Fiabilidad",   .762,
       "CFA", "Rasgo latente", "OPBP x QL",  "1/3 x 18",  "Fiabilidad",   .756,
       "CFA", "Rasgo latente", "OPBP x QL",    "0 x 18",  "Fiabilidad",   .633,
       "CFA", "Rasgo latente", "OPBP x QL",  "2/3 x 36",  "Fiabilidad",   .858,
       "CFA", "Rasgo latente", "OPBP x QL",  "1/3 x 36",  "Fiabilidad",   .856,
       "CFA", "Rasgo latente", "OPBP x QL",    "0 x 36",  "Fiabilidad",   .768,
       "CFA",       "Escalas",      "OPBP",       "2/3", "Correlación",   .991,
       "CFA",       "Escalas",      "OPBP",       "1/3", "Correlación",   .989,
       "CFA",       "Escalas",      "OPBP",         "0", "Correlación",   .960,
      "MCMC", "Rasgo latente",    "Modelo",          "",     "95% ICr",   .950,
       "CFA", "Rasgo latente",    "Modelo",          "",     "95% ICr",   .937,
      "MCMC", "Rasgo latente",        "QL",        "18",     "95% ICr",   .950,
      "MCMC", "Rasgo latente",        "QL",        "36",     "95% ICr",   .950,
       "CFA", "Rasgo latente",        "QL",        "18",     "95% ICr",   .933,
       "CFA", "Rasgo latente",        "QL",        "36",     "95% ICr",   .940
) %>% mutate_if(is.character, as.factor)
